**** Platform Direct3D 11:
Compiled code for kernel CSMain:
binary blob size 328:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
      cs_5_0
      dcl_globalFlags refactoringAllowed
      dcl_uav_typed_texture2d (float,float,float,float) u0
      dcl_input vThreadID.xy
      dcl_temps 2
      dcl_thread_group 8, 8, 1
   0: and r0.xy, vThreadID.xyxx, l(15, 15, 0, 0)
   1: utof r0.xy, r0.xyxx
   2: mul r0.yz, r0.xxyx, l(0.000000, 0.066667, 0.066667, 0.000000)
   3: and r1.x, vThreadID.y, vThreadID.x
   4: utof r0.x, r1.x
   5: mov r0.w, l(0)
   6: store_uav_typed u0.xyzw, vThreadID.xyyy, r0.xyzw
   7: ret 
// Approximately 0 instruction slots used




